apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sistema-noticias
      name: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80 
          envFrom:
            - configMapRef:
                name: configmap-sistema
          volumeMounts:
            - mountPath: /var/www/html/uploads
              name: imagens
            - mountPath: /tmp
              name: sessao
      volumes: 
        - name: imagens
          persistentVolumeClaim:
            claimName: imagens-pvc
        - name: sessao
          persistentVolumeClaim:
            claimName: sessao-pvc
      
  selector:
    matchLabels:
      app: sistema-noticias
  serviceName: svc-sistema-noticias
    