apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targerPort: 80
      nodePort: 30001
      #NodeRangePort=30000-32767
  selector:
    app: sistema-noticias