apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sessao-pvc
  namespace: alura-noticias
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce