apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
  namespace: alura-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targerPort: 80
      nodePort: 30000
      #NodeRangePort=30000-32767
  selector:
    app: portal-noticias