apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-portal-noticias
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configmap-portal
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias